### ISSUE TITLE
[todo] links at the bottom of the community and the copyright information have not been modified

### ISSUE THREAD

**Issue by jujube109** [WTFAcademy/WTF-Starknet#28]
![4562e0be6d190b174cfabcbd460b17c](https://user-images.githubusercontent.com/50389632/216862244-c6a777aa-6ba3-4009-a5f5-372362681bf1.png)
![image](https://user-images.githubusercontent.com/50389632/216862285-f15f17b2-7391-480d-bdc0-4cab974e2c42.png)
The three links point to the docusaurus community

**Comment by AmazingAng** [comment]
Fixed
